@param String message

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <h1 class="mt-5">Hello, Jte World!</h1>
    <p class="lead">This is a simple Jte template.</p>
    <p>${message}</p>
</div>
</body>
</html>
